import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider"; // Import the wrapper we just made

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}